# Generated by Django 6.0.1 on 2026-02-05 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formmodel',
            name='img',
        ),
        migrations.RemoveField(
            model_name='formmodel',
            name='last_modified',
        ),
    ]
