# Generated by Django 6.0.1 on 2026-02-06 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_loginuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginuser',
            old_name='usename',
            new_name='username',
        ),
    ]
